name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go mod download
    - name: Get Devtools
      run: make setup
    - name: Lint
      run : make lint
    - name: Build
      run: make
    - name: Test
      run: make test

  image_build:
    name: Image Build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: make build-image IMAGE_PREFIX=docker.pkg.github.com/pfnet-research/
